### ISSUE TITLE
Icons are black on dark theme

### ISSUE THREAD

**Issue by mutageneral** [23Bluemaster23/EdgeFox#2]
A lot of the icons are black on dark theme when they are supposed to be white. 
![image](https://user-images.githubusercontent.com/62779748/115248373-a0321300-a0f5-11eb-9ce2-5ba0a216a7f3.png)
The white theme has no problems because the icons needs to be black on white theme.
![image](https://user-images.githubusercontent.com/62779748/115248872-10409900-a0f6-11eb-8bca-92514e740a11.png)
I used the release 1.2
This is my first time doing userchrome stuff, so maybe I fucked up.
Tanks

**Comment by 23Bluemaster23** [comment]
you have to activate the option:

`svg.context-properties.content.enabled`

in about:config

**Comment by 23Bluemaster23** [comment]
I'm sorry for the delay

**Comment by mutageneral** [comment]
No worries! Works perfectly now tanks!
